<a href="https://colab.research.google.com/github/Dev-BelaCruz/Banco-de-dados/blob/main/50_elementos_e_03_dimens%C3%B5es_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importando a biblioteca numpy
import numpy as np

# Criando uma matriz (array) com 50 elementos e reorganizando para 3 dimensões (2x5x5)
v = np.array(range(50)).reshape(2, 5, 5)

# Exibindo as informações da matriz
print('Shape = ', v.shape)           # Mostra o formato (dimensões) da matriz
print('Número de dimensões = ', v.ndim)  # Mostra o número de dimensões
print('Número de elementos = ', v.size)  # Mostra o total de elementos
print('Tensor v = \n', v)            # Mostra o tensor (matriz 3D) criado


Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  50
Tensor v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
